### ISSUE TITLE
Aggiungere script auto-compilazione tabelle requisiti

### ISSUE THREAD

**Issue by RiccardoTonioloDev** [SWATEngineering/Docs#108]
Si trova [qui](https://github.com/SWATEngineering/Docs/blob/56-aggiungere-specifica-sensori-adr/src/2_RTB/AnalisiDeiRequisiti/content.typ) al branch numero 56 (publico su GitHub)

**Comment by ranghetto** [comment]
Se e' presente perche' bisogna aggiungerlo?

**Comment by RiccardoTonioloDev** [comment]
> Se e' presente perche' bisogna aggiungerlo?

È presente non nel main e non nel dev, ma solo ne branch 56.
Bisogna prelevarlo da li e metterlo nel nuovo branch.

**Comment by RiccardoTonioloDev** [comment]
Dove l'hai aggiunto?

**Comment by ranghetto** [comment]
[qui](https://github.com/SWATEngineering/Docs/pull/125/commits/7f94f88c87c59044664dce76af0d4ee893c94eb3)
