### ISSUE TITLE
Creazione templates in Typst

### ISSUE THREAD

**Issue by ranghetto** [SWATEngineering/Docs#11]
- [x] Verbali Interni
- [x] Verbali Esterni
- [x] Documento Normale
- [x] Lettera Presentazione

**Comment by ranghetto** [comment]
Aggiornata la size da `small` a `tiny`

**Comment by ranghetto** [comment]
[Repo](https://github.com/SWATEngineering/Templates)

**Comment by lonewalker0** [comment]
aggiornare il footer del main.typ mettendo 1 of 1
