### ISSUE TITLE
Sistemare i casi d'uso

### ISSUE THREAD

**Issue by RiccardoTonioloDev** [SWATEngineering/Docs#110]
Sono stati rimossi alcuni sensori (controllare [qui](https://app.diagrams.net/#G1BtShhB-LSVF4q9EDe2VGWaCowvjYHszh) i sensori con sopra le X rosse), e di conseguenza:
- [x] Sistemare gli indici;
- [x] Rimuovere e ricompattare i disegni.

**Comment by RiccardoTonioloDev** [comment]
Hai ricompattato i disegni?

**Comment by ranghetto** [comment]
Fatto

**Comment by RiccardoTonioloDev** [comment]
lgtm (posso direttamente chiudere la issue?)
