### ISSUE TITLE
Modificare GitHub action per la vetrina

### ISSUE THREAD

**Issue by RiccardoTonioloDev** [SWATEngineering/Docs#121]
Guardare come hanno fatto i progetti degli anni scorsi (distinzione tra documentazione interna ed esterna)

**Comment by ranghetto** [comment]
Ha un impatto cosi' elevato?

**Comment by ranghetto** [comment]
Per quello dico, a me non sembra piu' chiaro, aggiunge un layer di cartelle a caso a mio avviso, non per forza dobbiamo fare uguale agli anni scorsi. Poi se dici: "il prof. vuole cosi', punto", si fa.
