### ISSUE TITLE
Aggiungere termini glossario mancanti

### ISSUE THREAD

**Issue by ranghetto** [SWATEngineering/Docs#132]
File analizzato: ./src/2_RTB/PianoDiProgetto/sections/Pianificazione.typ
Elementi mancanti:
milestone, baseline

File analizzato: ./src/2_RTB/PianoDiProgetto/sections/Introduzione.typ
Elementi mancanti:
product baseline, customer acceptance, requirements and technology baseline

File analizzato: ./src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
Elementi mancanti:
context switch

File analizzato: ./src/2_RTB/PianoDiProgetto/sections/ModelloDiSviluppo.typ
Elementi mancanti:
its, sprint retrospective, item, sprint review

File analizzato: ./src/2_RTB/PianoDiProgetto/sections/PianificazioneSprint/DecimoSprint.typ
Elementi mancanti:
materialized views

File analizzato: ./src/2_RTB/PianoDiProgetto/sections/PianificazioneSprint/QuintoSprint.typ
Elementi mancanti:
archittetura

File analizzato: ./src/2_RTB/PianoDiProgetto/sections/PianificazioneSprint/NonoSprint.typ
Elementi mancanti:
retention policy, broker, portabilità, efficienza, batch, topic, scalabilità

**Comment by RiccardoTonioloDev** [comment]
Ho aggiunto i termini nel branch 122-aggiungere-dettaglio-uml poiché una volta fatto rebase del ramo, mi andava a fallire. Appena viene mergeato, non avremmo più problemi nel main.
