### ISSUE TITLE
Documento scelte tecnologiche

### ISSUE THREAD

**Issue by simocare** [SWATEngineering/Docs#138]

**Comment by ranghetto** [comment]
[Link al documento](https://docs.google.com/document/d/1LgPtgMc8V8jrrDQuuTt2kgsur7CR7U40aJ7ZmdbRtPg/edit)

**Comment by Dovid308** [comment]
Il documento va considerato ad uso interno?

**Comment by ranghetto** [comment]
Io lo inserirei in un documento, e' comunque qualcosa in piu'

**Comment by ranghetto** [comment]
Ottimo, grazie, allora lo teniamo per noi e lo usiamo durante il colloquio
