### ISSUE TITLE
DDB6

### ISSUE THREAD

**Issue by simocare** [SWATEngineering/Docs#140]

**Comment by ranghetto** [comment]
[Link al documento](https://docs.google.com/presentation/d/1kGLDBbHYUyLR1I9Nq5uIEyH1NsV804xxuTIkyGt4Cys/edit#slide=id.g298b23b877a_0_51)

**Comment by Dovid308** [comment]
Magari introdurrei come dubbio qualcosa di legato alla finestra rtb, anche solo per portarci l'attenzione. 
Non lo so, magari una roba del tipo : come modificare la pianificazione in senza una data ipotetica per la revisione? 
Ma comunque vedi te se ha senso mettere una roba del genere. Per me il ddb è approvato.

**Comment by ranghetto** [comment]
Non metterei una cosa di questo tipo semplicemente perche' in realta' mettere a dopo natale l'RTB ci porta solo che vantaggi, non credo proprio che la pianificazione generale si spostera' piu' di tanto

**Comment by Dovid308** [comment]
bon easy vedi te!

**Comment by RiccardoTonioloDev** [comment]
> Non metterei una cosa di questo tipo semplicemente perche' in realta' mettere a dopo natale l'RTB ci porta solo che vantaggi, non credo proprio che la pianificazione generale si spostera' piu' di tanto

Approvo totalmente

**Comment by RiccardoTonioloDev** [comment]
Lgtm
