### ISSUE TITLE
Miglioramento PdP

### ISSUE THREAD

**Issue by simocare** [SWATEngineering/Docs#149]
- [x] Stesura terzo  consuntivo;
- [x] Stesura quarto  consuntivo;
- [x] aggiustare i grafici del documento (dovrebbero essere tutti come quello del 2o consuntivo, quindi coi grafici 3d e i dati indicati, con l'aggiunta della percentuale);
- [x] correggere nella Pianificazione i tipi di sensori indicati, secondo quelli accordati;
- [x] correggere il preventivo del terzo sprint, altrimenti è troppo discorde con quello che abbiamo stabilito all'inizio di quello sprint (ad esempio nella distribuzione dei ruoli). Magari dare un occhi a quelli successivi e controllare che siano realistici/sensati.
- [x] ribilanciamento ore

**Comment by simocare** [comment]
- In più aggiustare i grafici del documento (dovrebbero essere tutti come quello del 2o consuntivo, quindi coi grafici 3d e i dati indicati, con l'aggiunta della percentuale).

**Comment by ranghetto** [comment]
Bloccato da #155 #156 e #157

**Comment by simocare** [comment]
Per creare/aggiornare il consuntivo di uno sprint è necessario:
- aggiornare il file su drive Areogrammi (Dati-Prev-Cons), creando tabella di preventivo e consuntivo, sulla base delle esistenti, basandosi sui dati presenti nel foglio OreSprint di Time & Resources
- creare: cartella NumeroSprint con NumeroSprint.typ, ore_consuntivo.csv e ore_preventivo.csv
- copiare un NumeroSprint.typ da quelli esistenti
- aggiornare la riga di codice
>  `#let sprint = trace.at(numerodellosprint)`
- aggiornare i grafici (scaricati da Areogrammi, ovviamente aggiornandone l'intervallo di riferimento)

Questo considerando che l'inserimento dei dati in ore_preventivo, ore_consuntivo e trace dovrebbe essere automatizzato.

**Comment by simocare** [comment]
I grafici presenti nello sprint 1 e 2 non sono aggiornati
