### ISSUE TITLE
Algoritmo fetch automatico dati consuntivo

### ISSUE THREAD

**Issue by ranghetto** [SWATEngineering/Docs#156]

**Comment by simocare** [comment]
Cosa cambia col nuovo script Typst in breve:
una cartella per ogni consuntivo e all'interno di essa 2 csv; ore_preventivo e ore_consuntivo (che necessitano di avere i dati aggiornati rispetto al file Sheets Areogrammi). I valori sono inseriti come nella tabella su Areogrammi. A che membro corrisponde ogni riga? le righe vengono inserite ordinate, per il cognome della persona.

Il significato trace.csv rimane invariato, riga 0 corrisponde al budget dell'inizio del progetto, le successive corrispondono ognuna ad uno sprint in ordine cronologico. Il primo valore indica il residuo di ore e il secondo di budget (anche questi da recuperare da Areogrammi).

**Comment by simocare** [comment]
![Image](https://github.com/SWATEngineering/Docs/assets/126779184/2e962b03-e211-4ecf-af8d-0e7a2504ebee)

C'è un problema con l'indicazione dello sprint: i nostri sprint iniziano il venerdì e durano una settimana, google sheets considera di default la settimana a partire da domenica, quindi sarebbe da modificare questa parte di codice oppure modificare la formula sul documento Time & Resource Manager il giorno da cui partire nella numerazione delle settimane.
