### ISSUE TITLE
NdP documentazione fine sprint

### ISSUE THREAD

**Issue by ranghetto** [SWATEngineering/Docs#157]
Normare le seguenti azioni di fine sprint:
- [ ] creare un preventivo per la seconda settimana da quel momento
- [x] creare consuntivo dello sprint passato
- [ ] calcolare/usare le metriche del PdQ rispetto allo sprint appena svolto

Done by #161

**Comment by simocare** [comment]
> Normare le seguenti azioni di fine sprint:
> 
>     * [ ]  creare un preventivo per la seconda settimana da quel momento
> 
>     * [x]  creare consuntivo dello sprint passato
> 
>     * [ ]  calcolare/usare le metriche del PdQ rispetto allo sprint appena svolto

La prima dipende dal periodo di preventivo che scegliamo, la terza non si può ancora fare perché non è ancora definito bene il contenuto del pdq.

**Comment by simocare** [comment]
blocked by #161

**Comment by simocare** [comment]
Serve documentare anche l'utilizzo dello script che controlla che i termini da glossario nel testo abbiano la G.
