### ISSUE TITLE
Issue(ona) AdR

### ISSUE THREAD

**Issue by ranghetto** [SWATEngineering/Docs#160]
Verifica e Miglioramento dell'_Analisi dei Requisiti_

**Comment by simocare** [comment]
- La UC3.3 (e UC3.5) andrebbe divisa in sotto-casi, uno per ogni tipo di informazioni indicata;
- UC5 è troppo generico, o si mette come viene segnalato il superamento della soglia specificando in che modo avviene, oppure si toglie la parte della notifica;
- Nell'UC 2.6 bisogna capire cosa si vuole mettere.

**Comment by simocare** [comment]
- Migliorerei la definizione di glossario di "Sistema", rendendola meno generica e più attinente al nostro caso e al suo significato in AdR

**Comment by Dovid308** [comment]
-alcuni casi d'uso a seguito del inserimento dell'unità di misure delle misuarazioni sono più specifici dei requisiti, manca l'aggiornamento dei requisiti corrispondenti. (Bacini Idirici, pioggia)

**Comment by Dovid308** [comment]
- perchè congestione stradale e intensità traffico sono due requisiti separati?

**Comment by RiccardoTonioloDev** [comment]
> * La UC3.3 (e UC3.5) andrebbe divisa in sotto-casi, uno per ogni tipo di informazioni indicata;
> * UC5 è troppo generico, o si mette come viene segnalato il superamento della soglia specificando in che modo avviene, oppure si toglie la parte della notifica;
> * Nell'UC 2.6 bisogna capire cosa si vuole mettere.

1.1) Direi di dividerlo in "panel per la visualizzazione su mappa + disponibilità" e "panel per vedere informazioni numeriche relative alla colonnina in se;
1.2) Penso che la percentuale si possa mettere direttamente sul puntatore della bicicletta in se (almeno al tempo era stata intuita così).
2) Sono parzialmente d'accordo, nel senso che negli UC vanno trattati gli scenari, poi però si va a disambiguare con i vincoli funzionali (ahimè però nemmeno nei vincoli sono specificate le soglie che genererebbero una notifica se superate).
3) È chiaro com'è, ovvero un contatore numerico che rappresenta la media degli ultimi 5 minuti.

**Comment by RiccardoTonioloDev** [comment]
> * Migliorerei la definizione in glossario di "Sistema", rendendola meno generica e più attinente al nostro caso e al suo significato in AdR

Concordo

**Comment by RiccardoTonioloDev** [comment]
> * perchè congestione stradale e intensità traffico sono due requisiti separati?

Assolutamente da rimuovere.

**Comment by RiccardoTonioloDev** [comment]
Vedo che ogni scenario principale non termina con il compimento di quanto enunciato dal titolo, sbaglio o è un errore?

**Comment by RiccardoTonioloDev** [comment]
Che il sistema si debba occupare dei dati relativi alla congestione stradale è obbligatorio, ma che li faccia visualizzare è Opzionale.
Incoerenza.
- [ ] TO DISCUSS

**Comment by RiccardoTonioloDev** [comment]
Vedo che viene menzionato _Glossario v1.0_, non ci dovrebbe andare l'underscore? non dovrebbe essere il nome letterale del file?
- [ ] TO DISCUSS

**Comment by RiccardoTonioloDev** [comment]
Più che dire "L'attore accede al sistema" che poi sarebbe "l'amministratore pubblico", non sarebbe meglio dire "accede alla piattaforma di visualizzazione", o qualcosa del genere?
- [ ] TO DISCUSS

**Comment by RiccardoTonioloDev** [comment]
UC1.2 Non specifica che tipo di dati sono visualizzabili sulla tabella.
- [ ] TO DISCUSS

**Comment by RiccardoTonioloDev** [comment]
Manca da:
 - [ ] finire con la disambiguazione dei vincoli;
 - [ ] l'aggiunta dei vincoli di performance;
 - [ ] l'atomizzazione di vincoli dove sono troppo grossi;
 - [ ] verifica walkthough man mano che risolvo i punti precedenti.
