### ISSUE TITLE
Modifiche script consuntivo

### ISSUE THREAD

**Issue by ranghetto** [SWATEngineering/Docs#170]
- [x] non mostrare i valori col . quando dopo la virgola c'è solo 0;
- [x] al posto degli zeri nelle tabelle, mettere un "-";
- [ ] ~aggiungere le date di inizio e fine sprint per ognuno di essi.~

**Comment by RiccardoTonioloDev** [comment]
@ranghetto @simocare ricordo che queste modifiche erano state proposte da uno di voi.
Vi dico già che il terzo punto non si può fare perché lo script calcola le ore da consuntivo usando il numero della settimana e non il vero sprint.
Ditemi voi se avete delle shortcut che vi vengono in mente a riguardo.

**Comment by simocare** [comment]
> @ranghetto @simocare ricordo che queste modifiche erano state proposte da uno di voi. Vi dico già che il terzo punto non si può fare perché lo script calcola le ore da consuntivo usando il numero della settimana e non il vero sprint. Ditemi voi se avete delle shortcut che vi vengono in mente a riguardo.

Vai tranquillo non è importante alla fine quel punto. Comunque abbiamo modificato il cacolo della week nello sheet in modo che corrisponda precisamente con lo sprint (venerdì-giovedì) in modo che le metriche non siano più sballate.
