### ISSUE TITLE
DDB7

### ISSUE THREAD

**Issue by Dovid308** [SWATEngineering/Docs#174]

**Comment by simocare** [comment]
- "deciso di preservare pianificazione e preventivo per sprint;", secondo me per uno che non sa, non è molto chiaro cosa si intende in questa frase;
- si potrebbe aggiungere tra le difficoltà: coordinare lavori in parallelo sugli stessi documenti.

**Comment by nance97** [comment]
grazie @simocare 
- ho sostituito con "deciso di impiegare pianificazione e preventivi a breve termine" (ripensandoci, non credo menzionerò che ci siamo prima limitati alle sole revisioni, semplicemente abbiamo rimosso la pianificazione a lungo termine fino alla ca);
- aggiunto la difficoltà sopra
