### ISSUE TITLE
Creazione struttura Piano di Progetto

### ISSUE THREAD

**Issue by ranghetto** [SWATEngineering/Docs#24]
Creazione struttura iniziale Piano di Progetto

**Comment by simocare** [comment]
Con urgenza c'è da fare il "preventivo primo avanzamento", ovvero del primo sprint, perché di fatto siamo già nello sprint...

**Comment by RiccardoTonioloDev** [comment]
Domani vedo di stendere la struttura e di occuparmi di scrivere la parte relativa al "preventivo primo avanzamento", tuttavia servirebbe un modo per includere grafici a barre e a torta. @ranghetto io ho provato a cercare su internet, ma Typst non mi sembra li supporti per ora. Qualche idea?

**Comment by ranghetto** [comment]
Che non li supporti del tutto dubito, ci sarà qualche pacchetto esterno

**Comment by RiccardoTonioloDev** [comment]
Sisi, penso che opterò per la scelta delle immagini.

**Comment by RiccardoTonioloDev** [comment]
Sposto il compito a @nance97 . La struttura iniziale l'ho buttata giù. Basta che ti scarichi il branch associato alla issue.
