### ISSUE TITLE
Raffinamento analisi dei requisiti

### ISSUE THREAD

**Issue by RiccardoTonioloDev** [SWATEngineering/Docs#245]
- [x] Decidere se c'è o meno una sezione "requisiti di sicurezza";
  - [x] Se c'è non deve essere vuota.
- [x] Tutti i requisiti devono essere tracciati in una tabella (NON DEVONO ESISTERE REQUISITI DESCRITTI SOLO TESTUALMENTE);
- [x] Tutti i requisiti devono essere disciplinati, sistematici, quantificabili e **NON AMBIGUI**, quindi sistemare ad esempio sotto _requisiti di performance_ "bassa latenza" con un numero che quantifichi cos'è la bassa latenza e "pannelli non troppo complessi" con una forma più chiara di cosa siano pannelli troppo complessi.

**Comment by Dovid308** [comment]
Ho deciso di rimuovere la parte relativa alla sicurezza; 
aggiunti i requisiti in tabella;

**Comment by Dovid308** [comment]
Per il revisore chiedo di dare un occhiata anche "semantica" che in molte cose ero incerto.

**Comment by Dovid308** [comment]
Procedo anche ad andare a controllare che i cambiamenti precedenti siano riportati nel pdq
