### ISSUE TITLE
Inserire descrizione ruoli in Norme di Progetto

### ISSUE THREAD

**Issue by ranghetto** [SWATEngineering/Docs#25]
In particolare la definizione del ruolo di Responsabile
- corrispondenza
- gestione meetings (con odg)
- redazione verbali interni ed esterni

**Comment by ranghetto** [comment]
Per quanto riguarda il responsabile potremmo anche assegnargli il compito di scaricare i verbali esterni firmati una volta che ci arrivano e di immagazzinarli dentro una cartella apposita su G. Drive. In questo modo ce li abbiamo sempre belli ordinati

**Comment by RiccardoTonioloDev** [comment]
Per il prossimo meeting.

**Comment by RiccardoTonioloDev** [comment]
Per il responsabile:
• Gestire la comunicazione con la Proponente (e.g. mail o l’uso della
piattaforma Element);
• Preparare l’ordine del giorno per la successiva riunione, anche sulla base
dei punti individuati dagli altri componenti;
• Redigere i verbali interni ed esterni;
• Stendere e far progredire il documento “Piano di progetto”;
• Creare i diari di bordo;
• scaricare i verbali esterni convalidati e immagazzinarli dentro la cartella IncontriAziende/VerbaliEsterni_Convalidati su Google Drive.

**Comment by simocare** [comment]
Avevo iniziato a scrivere questa parte, ma non ho fatto il commit. Non so se può essere utile, comunque inserisco qui sotto quanto avevo scritto.

=== Ruoli
Con l'obbiettivo di garantire un'adeguata gestione dei compiti e delle attività da svolgere, vengono stabiliti sei ruoli, che si differenziano come incarichi e come responsabilità. Di seguito vengono elencati i ruoli con le relative competenze.

==== Responsabile
Il responsabile svolge un ruolo centrale come intermediario tra il il committente e il fornitore, fungendo da punto di riferimento per entrambe le parti. A questo ruolo spetta la responsabilità del coordinamento all'interno del gruppo di lavoro e rappresenta il punto di riferimento per eventuali dubbi o problematiche, che lo stesso inserirà nell'#glossary("ordine del giorno"). Inolte è incaricato dei seguenti incarichi:
- Corrispondenza con il committente e la proponente, sia tramite email che tramite Element;
- Organizzazione dei meeting, con le seguenti mansioni:
  - stesura dell'ordine del giorno, sulla base delle informazioni ricevute dai membri del gruppo;
  - redazione dei verbali interni ed esterni;
  - richiesta ai proponenti della firma dei verbali esterni e successiva organizzazione in apposita cartella su Drive;
- Stesura del DDB e presentazione;
- Stesura e progressione del PdP;
