### ISSUE TITLE
PdP update fine sprint 10

### ISSUE THREAD

**Issue by nance97** [SWATEngineering/Docs#250]
Ripianificare il preventivo con le 10 ore rimanenti e la pianificazione;
 - [x] aggiornare quello attuale (sprint 11)
 - [x] il successivo (sprint 12)
 - [x] creare il 13
 - [x] stendere consuntivo sprint 10
 - [x] rimuovere CA dal piano di progetto

**Comment by simocare** [comment]
Nella versione 1.1 aggiungi Giacomo e Nancy come verificatori
