### ISSUE TITLE
Upgrade a RC1 in Analisi dei Rischi

### ISSUE THREAD

**Issue by RiccardoTonioloDev** [SWATEngineering/Docs#266]
Aggiungere un punto migliorativo, ovvero il fatto che sono stati fissati gli orari dei meeting, al fine di fornire determinismo nello stabilire quando si ha effettivamente un meeting, senza possibilità di cambiare orario.

**Comment by Dovid308** [comment]
@RiccardoTonioloDev nel senso che se effettivamente scegliamo un orario una volta questo non puo essere cambiato?
