### ISSUE TITLE
Fase installazione api key

### ISSUE THREAD

**Issue by ranghetto** [SWATEngineering/Docs#293]
Aggiungere al manuale utente la fase di installazione, in particolare la creazione dell'API key per le biciclette

**Comment by ranghetto** [comment]
@nance97 Questa non c'e' ancora vero?

**Comment by nance97** [comment]
> [@nance97](https://github.com/nance97) Questa non c'e' ancora vero?

no, le API keys non sono menzionate nella fase di installazione al momento.
