### ISSUE TITLE
Il bot ha rimosso i verbali esterni

### ISSUE THREAD

**Issue by RiccardoTonioloDev** [SWATEngineering/Docs#302]
Il bot ha rimosso dei verbali esterni a questo commit `ca8420d4c471b96c2031cecb7530aa369eb331a8 ` (anche in un commit addietro).
Da capire come e perchè, e ovviamente fixare.
- [x] Fixare il bug;
- [x] Ricaricare verbali esterni persi (scaricarli dalle mail e ricaricarli o insomma trovare un modo per ritirarli su).

**Comment by ranghetto** [comment]
@RiccardoTonioloDev fixed, ricontrolla anche tu pls

**Comment by RiccardoTonioloDev** [comment]
Suppongo sia stata mergeata right? @ranghetto

**Comment by ranghetto** [comment]
Si si fixed
