### ISSUE TITLE
Raffinare procedura di pull request per documenti

### ISSUE THREAD

**Issue by RiccardoTonioloDev** [SWATEngineering/Docs#33]
- Specificare nelle NdP come e cosa va inserito nei commenti (tipo la chiusura della issue);
- Penso sarebbe una buona idea consigliare di creare un branch a partire dalla issue (così poi la pull request è collegata);
- Se assegnarla in review a tutti i verificatori ad un determinato istante o se ne basta solo uno.

**Comment by ranghetto** [comment]
- Non capisco cosa intendi nel primo punto
- Sicuramente si puo' scrivere
- Secondo me basta un singolo revisore per issue

**Comment by RiccardoTonioloDev** [comment]
1. Nei commenti della pull request è da scrivere "close #IdAddressedIssue" (dovrebbe essere scritto nell'NdP, ma è una piccolezza);
2. Ok;
3. Anche questo allora è da scrivere, perché per ora facciamo fare il lavoro ad entrambi:
    => Il prossimo sprint c'è un solo revisore, ma nel momento in cui magari ce ne saranno due, bisogna mettere nelle NdP una politica tipo FCFS per stabilire come funziona la presa in carico di uno solo dei due, per la revisione di qualsiasi cosa si debba revisionare.

**Comment by ranghetto** [comment]
1. Non è necessario scriverlo, è sicuramente una comodità ma non essenziale, si possono comunque chiudere a mano le issue (per la regola "non normiamo anche il modo in cui respiriamo").
2. -
3. Sono d'accordo che vada scritto, la politica sarebbe, più che FCFS: si prendono le issue nella corsia `Ready to review` in ordine di `Priority`, con la regola di un unico verificatore

Collegato al punto `3.`, spesso nelle NdP è scritto "i verificatori", va riportato al singolare.

**Comment by RiccardoTonioloDev** [comment]
Quindi proponi un unico verificatore per sprint per sempre?

**Comment by ranghetto** [comment]
In base al carico di lavoro, ma in linea generale si

**Comment by RiccardoTonioloDev** [comment]
Chiudo la issue. Quanto appena detto verrà trattato nel prossimo meeting.
