### ISSUE TITLE
Realizzare UML per i simulatori

### ISSUE THREAD

**Issue by RiccardoTonioloDev** [SWATEngineering/Docs#34]
Relativamente alla parte di progettazione, bisognerebbe stendere l'UML per mostrare le dipendenze tra le varie classi.

**Comment by RiccardoTonioloDev** [comment]
Ottima domanda, è da chiedere al professore di laboratorio. Intanto magari è da pensare e fare.

**Comment by ranghetto** [comment]
Done in #101
