### ISSUE TITLE
Aggiornamento glossario PdP

### ISSUE THREAD

**Issue by simocare** [SWATEngineering/Docs#42]
Aggiornare il glossario coi nuovi termini utilizzati nei documenti PdP.

**Comment by simocare** [comment]
Inserire definizione dei nuovi termini di glossario utilizzati nel PdP

**Comment by RiccardoTonioloDev** [comment]
Se check_glossary.py nelle automazioni, non ti da problemi, allora puoi pure chiudere la query.

**Comment by simocare** [comment]
La issue era per l'inserimento delle definizioni, quando avrò aggiunto almeno quelle utilizzate nel PdP, la chiudo.

**Comment by RiccardoTonioloDev** [comment]
ottimo. Hai fatto rebase sul branch nella quale stai lavorando al PdP? Perché sennò ti mancano tutte quelle vecchie, aggiunte di recente.

**Comment by simocare** [comment]
Prima di inserire le definizioni faccio il rebase.
