### ISSUE TITLE
[TO DELETE] aggiungere specializzazione nel UC1

### ISSUE THREAD

**Issue by lonewalker0** [SWATEngineering/Docs#59]

**Comment by RiccardoTonioloDev** [comment]
@lonewalker0 @Dovid308 Cosa intendevate con aggiungere specializzazione nell'UC1?

**Comment by Dovid308** [comment]
Non è propriamente un idea nostra ma più una questione sollevata dalla Proponente ieri durante la riunione al momento della discussione del caso d'uso 1. 
Sostanzialmente si diceva che nella dashboard iniziale di dovessero avere anche dei casi aggregati, come temperatura media...
Io sinceramente avevo già dato questa interpretazione al caso d'uso già presente sugli indicatori numerici.

**Comment by lonewalker0** [comment]
lo volevano visualizzato già sulla dashboard senza selezionare il sensore, per questo la specializzazione
