### ISSUE TITLE
Verbale 31-10

### ISSUE THREAD

**Issue by ranghetto** [SWATEngineering/Docs#6]
[Verbale](https://www.overleaf.com/project/65413dfaf9cf8e8d78e56ba0)

**Comment by ranghetto** [comment]
Inviata revisione (v0.1.0), le modifiche da apportare sono state segnate come al solito come commenti di revisione in Overleaf
@simocare @nance97

**Comment by nance97** [comment]
Apportate le modifiche richieste @ranghetto
