### ISSUE TITLE
[TO DELETE] uc5 requisito opzionale

### ISSUE THREAD

**Issue by lonewalker0** [SWATEngineering/Docs#60]

**Comment by RiccardoTonioloDev** [comment]
@lonewalker0 @Dovid308 mi ricordate questo cosa significava?

**Comment by Dovid308** [comment]
Credo fosse il requisito su modificare lo stato del sensore, cioè con il flusso inverso, dovresti cambiare i requisiti che ne derivano in opzionali. Credo che come caso d'uso vada bene anche così in realtà
