### ISSUE TITLE
AdR Aggiungere ai requisiti i casi d'uso associati

### ISSUE THREAD

**Issue by RiccardoTonioloDev** [SWATEngineering/Docs#65]

**Comment by RiccardoTonioloDev** [comment]
Serve una quarta colonna che indica la sorgente di tale requisito (e.g. se viene da un caso d'uso, o da una decisione interna)

**Comment by RiccardoTonioloDev** [comment]
Appena visto che c'è una tabella sotto. Io la porterei allo stesso piano dei requisiti.

**Comment by ranghetto** [comment]
Fatto e presente in #101
