### ISSUE TITLE
Esplorazione alternative a Notion

### ISSUE THREAD

**Issue by ranghetto** [SWATEngineering/Docs#7]
Stiamo per esaurire lo spazio Notion, bisogna trovare un'alternativa con le stesse caratteristiche, che non ci dia limite sul numero di documenti/blocchi da scrivere [ClickUp](https://clickup.com) potrebbe essere una buona alternativa, da verificare.

**Comment by simocare** [comment]
Tutti i seguenti con il piano "free" hanno spazio illimitato.
- Mem
https://get.mem.ai/

- Microsoft Loop
incluso nel Microsoft 365, che abbiamo disponibile tramite Unipd
https://loop.microsoft.com/learn

- Slab
https://slab.com/

- Anytype
Questo sembra una copia di Notion
https://anytype.io/

**Comment by Dovid308** [comment]
https://coda.io/ potrebbe essere una valida alternativa.

Ha pur sempre delle limitazioni, ma ad occhio mi sembrano accettabili; 

Inoltre buona portabilità da notion;

**Comment by RiccardoTonioloDev** [comment]
**CONSIDERAZIONI SU** [Coda](https://coda.io/)

- identico a Notion (si usa allo stesso modo, stesse shortcut, presenti gli stessi costrutti);
- sembrerebbe gratis e illimitato (per un uso non enterprise);
- _non chiaro il sistema di pricing_ (Guarda [qui](https://coda.io/pricing)).

Verdetto personale: _valido candidato_.

**Comment by ranghetto** [comment]
Sono d'accordo nel dire che sia contorto il sistema di pricing. Da valutare attentamente per evitare di dover cambiare strumento nuovamente.

**Comment by simocare** [comment]
Essendo che NON è gratuito per la parte di creazione pagine/documenti, ma solo per la modifica, non è inutilizzabile nel nostro caso?

**Comment by Dovid308** [comment]
Probabilmente la cosa del DockMaker è valida solo nel caso in cui si vogliano andare ad avere documenti con più di 1000 righe o 50 oggetti (tabelle o simili), fino a che non si rompono questi limiti tutto funziona gratuitamente; 

Ho provato a impostare uno strumento di Time Control, che a me onestamente piace per come è ora.
Il problema è che 1000 righe corrispondono a 1000 "sessioni", che secondo me sono comunque poche. 

Una soluzione potrebbe essere quella di mantenere questo per la gestione delle ore "produttive", e andarne a creare delle copie però 'ad personam' in maniera tale che comunque le ore (nella totalità intese come non produttive) sarebbero comunque tracciate e visibili da tutto il  team.

**Comment by Dovid308** [comment]
Microsoft loop non è comunque integrato nel pacchetto 365 di unipd.

**Comment by simocare** [comment]
# Considerazione su ClickUp
Spoiler: il free plan è inutilizzabile.
![ClickUp.pdf](https://github.com/SWATEngineering/Docs/files/13324636/ClickUp.pdf)

**Comment by RiccardoTonioloDev** [comment]
Al momento sto cercando di ricreare quanto avevamo in Notion, su Google Drive, usando Google Fogli e Google Documenti. Poi vedremo se utilizzarlo o meno, ma i benefit sono:

- Siamo sicuri che sia gratis per sempre;
- Permette una perfetta organizzazione di documenti in cartelle/sottocartelle e file;
- Tutto viene raccolto nello stesso posto;
- Siamo ASSOLUTAMENTE SICURI che non ci sono problemi di limitatezza in qualsiasi cosa;
- Permette la collaborazione in live;
- Il tracking delle ore si può fare spettacolarmente in google fogli (si può creare veramente un gran cruscotto per il resource management).

**Comment by RiccardoTonioloDev** [comment]
Si è scelto all'unanimità di passare alla suite Google Drive.
