### ISSUE TITLE
Creazione DDB 02

### ISSUE THREAD

**Issue by ranghetto** [SWATEngineering/Docs#8]

**Comment by RiccardoTonioloDev** [comment]
Bloccato in quanto attendo incontro con la Proponente, venerdì 10 novembre 2023, per poter completare e ultimare il ddb.

**Comment by RiccardoTonioloDev** [comment]
Sbloccato, in quanto è stato fatto l'incontro con la Proponente, e quindi il ddb può essere completato.

**Comment by ranghetto** [comment]
Nella cartella drive del team non c'è, dove lo trovo?

**Comment by ranghetto** [comment]
[REV]

- slide 2:
	- "della repository" -> "del repository", lui lo chiama sempre al maschile;
- slide 4:
	- cambierei da "nessuna difficolta' significativa" a mettere direttamente l'elenco di quelle non significative. Sono pur sempre difficolta' e non credo gli interessi la differenza;

**Comment by RiccardoTonioloDev** [comment]
Le modifiche richieste sono state apportate.

**Comment by Dovid308** [comment]
Mi sembra bene!

**Comment by ranghetto** [comment]
[REV]

LGTM! approvato
